// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HabitUpdateController from "./habit_update_controller"
application.register("habit-update", HabitUpdateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
